import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Book sidebar configuration
 * Uses autogenerated sidebars with _category_.json files for module organization
 */
const sidebars: SidebarsConfig = {
  // Autogenerate sidebar from docs folder structure
  // Each module uses _category_.json for ordering and metadata
  bookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
